---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: etcd
deploy:
  kubectl:
    manifests:
    - example/00-namespace-garden.yaml
  kustomize:
    paths:
    - example/gardener-local/etcd
---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: controlplane
requires:
- configs: ["etcd"]
build:
  local:
    useBuildkit: true
    concurrency: 1
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/apiserver
    docker:
      dockerfile: Dockerfile.local
      target: apiserver
      buildArgs:
        VERSION: "{{.VERSION}}"
  - image: eu.gcr.io/gardener-project/gardener/controller-manager
    docker:
      dockerfile: Dockerfile.local
      target: controller-manager
      buildArgs:
        VERSION: "{{.VERSION}}"
  - image: eu.gcr.io/gardener-project/gardener/scheduler
    docker:
      dockerfile: Dockerfile.local
      target: scheduler
      buildArgs:
        VERSION: "{{.VERSION}}"
deploy:
  helm:
    releases:
    - name: gardener-controlplane
      chartPath: charts/gardener/controlplane
      namespace: garden
      createNamespace: true
      wait: true
      artifactOverrides:
        global:
          apiserver:
            image: eu.gcr.io/gardener-project/gardener/apiserver
          controller:
            image: eu.gcr.io/gardener-project/gardener/controller-manager
          scheduler:
            image: eu.gcr.io/gardener-project/gardener/scheduler
      imageStrategy:
        helm: {}
      valuesFiles:
      - charts/gardener/controlplane/values-local.yaml
---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: local-env
requires:
- configs: ["controlplane"]
deploy:
  kubectl:
    manifests:
    - example/gardener-local/gardenlet/secret-bootstrap-token.yaml
  kustomize:
    paths:
    - example/provider-local/overlays/skaffold
---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: gardenlet
requires:
- configs: ["local-env"]
build:
  local:
    useBuildkit: true
    concurrency: 1
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/gardenlet
    docker:
      dockerfile: Dockerfile.local
      target: gardenlet
      buildArgs:
        VERSION: "{{.VERSION}}"
  - image: eu.gcr.io/gardener-project/gardener/resource-manager
    docker:
      dockerfile: Dockerfile.local
      target: resource-manager
      buildArgs:
        VERSION: "{{.VERSION}}"
  - image: eu.gcr.io/gardener-project/gardener/seed-admission-controller
    docker:
      dockerfile: Dockerfile.local
      target: seed-admission-controller
      buildArgs:
        VERSION: "{{.VERSION}}"
deploy:
  helm:
    releases:
    - name: gardener-gardenlet
      chartPath: charts/gardener/gardenlet
      namespace: garden
      createNamespace: true
      wait: true
      artifactOverrides:
        global:
          gardenlet:
            image: eu.gcr.io/gardener-project/gardener/gardenlet
          # dummy artifact overrides to make skaffold load images into cluster
          resource-manager:
            image: eu.gcr.io/gardener-project/gardener/resource-manager
          seed-admission-controller:
            image: eu.gcr.io/gardener-project/gardener/seed-admission-controller
      setValueTemplates:
        global:
          gardenlet:
            # on a local cluster, skaffold uses a local immutable tag for artifacts,
            # overwrite our image vector to use the image that was just built
            # see https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works
            imageVectorOverwrite: |
              images:
              - name: gardener-resource-manager
                sourceRepository: github.com/gardener/gardener
                repository: eu.gcr.io/gardener-project/gardener/resource-manager
                tag: "{{.IMAGE_TAG5}}"
              - name: gardener-seed-admission-controller
                sourceRepository: github.com/gardener/gardener
                repository: eu.gcr.io/gardener-project/gardener/seed-admission-controller
                tag: "{{.IMAGE_TAG6}}"
      imageStrategy:
        helm: {}
      valuesFiles:
      - charts/gardener/gardenlet/values-local.yaml
---
apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: provider-local
requires:
- configs: ["gardenlet"]
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/provider-local
    docker:
      dockerfile: Dockerfile.local
      target: extension-provider-local
    sync:
      infer:
      - charts/gardener/provider-local/internal
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: gardener-extension-provider-local
      chartPath: charts/gardener/provider-local/extension
      namespace: extension-provider-local
      createNamespace: true
      wait: true
      artifactOverrides:
        image: eu.gcr.io/gardener-project/gardener/extensions/provider-local
      imageStrategy:
        helm: {}
