apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: local
spec:
  type: local
  regions:
  - name: local
  kubernetes:
    versions:
    - version: 1.22.0
    - version: 1.21.0
    - version: 1.20.0
    - version: 1.19.0
    - version: 1.18.0
  machineTypes:
  - cpu: "1"
    gpu: "0"
    memory: 1Gi
    name: local
  machineImages:
  - name: local
    versions:
    - version: 1.0.0
      cri:
      - name: containerd
  providerConfig:
    apiVersion: local.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    machineImages:
    - name: local
      versions:
      - version: 1.0.0
        image: ghcr.io/gardener/machine-controller-manager-provider-local/node:sha-f733395
